trigger: none
pr:
  - master

variables:
- group: studadm-general-params
- name: imageName
  value: kurs-pm-data-api
- name: dockerfilePath
  value: '$(Pipeline.Workspace)/github/Dockerfile'
- name: tag
  value: '$(Build.SourceVersion)'

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: Cloud Excellence Team/cet-iac
      ref: main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - template: templates/test/npm-test.yml@cet-iac
    parameters:
      nodeVersion: '16.x'
  - template: templates/test/docker-test.yml@cet-iac
    parameters:
      dockerComposeFilePaths:
        - '$(Pipeline.Workspace)/github/docker-compose-unit-tests.yml'
        - '$(Pipeline.Workspace)/github/docker-compose-integration-tests.yml'
      dockerfilePath: $(dockerfilePath)
      imageName: $(imageName)
      tag: $(tag)
