trigger: none
pr:
  - master

variables:
  - group: studadm-general-params
  - name: imageName
    value: kurs-pm-data-api
  - name: dockerfilePath
    value: '$(Pipeline.Workspace)/github/Dockerfile'
  - name: tag
    value: '$(Build.SourceVersion)'

resources:
  repositories:
    - repository: stratus-templates
      type: git
      name: Cloud Excellence Team/stratus-templates
      ref: main

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: templates/security/security-scans.yml@stratus-templates
  parameters:
    break: false
    jobs:
    - job: test
      displayName: 'Test'
      steps:
      - template: /templates/test/npm.yml@stratus-templates
        parameters:
          nodeVersion: 20.x

      - template: /templates/test/docker.yml@stratus-templates
        parameters:
          dockerComposeFilePaths:
          - '$(Pipeline.Workspace)/github/docker-compose-unit-tests.yml'
          - '$(Pipeline.Workspace)/github/docker-compose-integration-tests.yml'
          dockerfilePath: $(dockerfilePath)
          imageName: $(imageName)
          tag: $(tag)
